baseURL = "https://brendanforster.com/"
languageCode = "en-US"
title = "brendanforster.com"
theme = "hugo-natrium-theme"

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"
  notes = "/notes/:slug/"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"

[[menu.main]]
    name = "Now"
    url = "/now/"
    weight = -110

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = -120

[params]
    description = "Just a site about me and what I've been up to"
