name = "Natrium"
license = "MIT"
licenselink = "https://github.com/neil-sabol/hugo-natrium-theme/blob/master/LICENSE.md"
description = "Natrium minimal theme"
homepage = "https://github.com/neil-sabol/hugo-natrium-theme"
tags = ["blog", "minimal", "personal", "responsive"]
features = ["blog", "taxonomies", "privacy"]
min_version = 0.25

[author]
  name = "Tim Krieger"
  homepage = "https://blog.mobybit.de"
  
[original]
  name = "Jonathan Rutheiser"
  homepage = "http://jrutheiser.com/"
  repo = "https://github.com/jrutheiser/hugo-lithium-theme"
